import './globals.css'
import type { Metadata } from 'next'

import { Tektur } from 'next/font/google'
import { Suspense } from 'react'
import Loading from './loading'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className="font-primary">
            <Suspense fallback={<Loading />} />
            <body className="text-white">{children}</body>
        </html>
    )
}
